// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snmzqrvxofgkzlzyxqft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNubXpxcnZ4b2Zna3psenl4cWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2NDQyODksImV4cCI6MjA1MDIyMDI4OX0.pMmmZPUKnf4SDuFjUwz_X4UqhJXuZsn-h7PrPb0S0f4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);